[theme]
primaryColor = "#46c57a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333F"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
